# Generated by Django 4.0.5 on 2022-06-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bike',
            old_name='year',
            new_name='end_year',
        ),
        migrations.AddField(
            model_name='bike',
            name='start_year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
